filebeat.autodiscover:
    providers:
        - type: docker
            # hints.enabled: true
          templates:
              - condition.contains:
                    docker.container.name: "${CONTAINER_NGINX}"
                config:
                  - module: nginx
                    access.input:
                      pipeline: "${PIPELINE_NGINX_ACCESS}"
                      type: container
                      paths:
                        - /var/lib/docker/containers/${data.docker.container.id}/*.log
                      stream: stdout
                    error.input:
                      type: container
                      paths:
                        - /var/lib/docker/containers/${data.docker.container.id}/*.log
                      stream: stderr

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]
  api_key: "${ELASTICSEARCH_API_KEY}"
  compression_level: 9
  indices:
    - index: "${INDEX_NGINX}"

setup.kibana:
  host: "${KIBANA_HOST}"

# logging:
#   level: debug
#   to_stderr: true
#   to_files: true
#   to_syslog: false
#   files:
#     path: /var/log/mybeat
#     name: mybeat.log
#     keepfiles: 7
#     rotateeverybytes: 10485760 # = 10MB
